# PART-1 : THEORETICAL QUESTIONS

## Tc What are the different data structures used in Tensorflow?. Give some examplesc

TensorFlow, a popular open-source machine learning framework developed by the Google Brain team, various data structures are used to represent and manipulate data efficiently. Some of the key data structures in TensorFlow include:

Tensors:

Tensors are the fundamental building blocks in TensorFlow.
They are multi-dimensional arrays with a fixed data type.

In [1]:
import tensorflow as tf

# Creating tensors
tensor_1d = tf.constant([1, 2, 3, 4, 5])
tensor_2d = tf.constant([[1, 2, 3], [4, 5, 6]])


2: Variables:

Variables are used to hold and update parameters during training.
They are typically used for model parameters like weights and biases.

In [4]:
variable = tf.Variable(initial_value=[1.0, 2.0, 3.0], trainable=True)
variable

<tf.Variable 'Variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

3 : Constants:

Constants are immutable tensors whose values cannot be changed after initialization.
They are used for fixed values that do not need to be updated during training.

In [5]:
constant = tf.constant([3.14, 2.71])
constant

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3.14, 2.71], dtype=float32)>

These data structures play a crucial role in constructing and executing computational graphs in TensorFlow, allowing for efficient representation and manipulation of data in the context of machine learning models. Note that the specific APIs and usage may vary between TensorFlow versions.

## Cc How does the TensorFlow constant differ from a TensorFlow variable? Explain with an examplec

Immutability:

Constants: Once a constant is created, its value cannot be changed. Constants are used for fixed values that do not need to be updated during training.
Variables: Variables, on the other hand, are designed to hold values that may need to be updated and modified during training. They are typically used to represent model parameters like weights and biases.
Usage in Training:

Constants: Ideal for values that remain constant throughout the training process, such as hyperparameters or fixed data.
Variables: Used for trainable parameters that are updated during the training process, such as weights and biases in a neural network.
Creation Syntax:

Constants: Created using the tf.constant() function, specifying the initial value.
Variables: Created using the tf.Variable() class, often with an initial value. Variables can be updated during training using operations like assign or by directly modifying their values.

In [6]:
import tensorflow as tf


constant_value = tf.constant([1.0, 2.0, 3.0], dtype=tf.float32)
initial_variable_value = tf.constant([4.0, 5.0, 6.0], dtype=tf.float32)
variable = tf.Variable(initial_value=initial_variable_value)

print("Constant Value:", constant_value.numpy())
print("Variable Value:", variable.numpy())

variable.assign([7.0, 8.0, 9.0])

print("Constant Value:", constant_value.numpy())
print("Updated Variable Value:", variable.numpy())


Constant Value: [1. 2. 3.]
Variable Value: [4. 5. 6.]
Constant Value: [1. 2. 3.]
Updated Variable Value: [7. 8. 9.]


## =c Describe the process of matrix addition, multiplication, and elementDwise operations in TensorFlow.


In TensorFlow, matrix addition, multiplication, and element-wise operations are fundamental operations for manipulating tensors, particularly when working with neural networks and other machine learning models. Let's describe each of these operations:



Matrix Addition:
Matrix addition is a straightforward element-wise addition of corresponding elements in two matrices of the same shape. In TensorFlow, you can use the tf.add() function for matrix addition.

In [7]:
import tensorflow as tf

# Create two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Matrix addition
result_addition = tf.add(matrix_a, matrix_b)

print("Matrix A:\n", matrix_a.numpy())
print("Matrix B:\n", matrix_b.numpy())
print("Matrix Addition Result:\n", result_addition.numpy())

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Addition Result:
 [[ 6  8]
 [10 12]]


Matrix Multiplication:
Matrix multiplication involves multiplying the elements of one matrix by the elements of another matrix according to specific rules. In TensorFlow, you can use the tf.matmul() function for matrix multiplication.

In [8]:
# Create two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Matrix multiplication
result_multiplication = tf.matmul(matrix_a, matrix_b)

print("Matrix A:\n", matrix_a.numpy())
print("Matrix B:\n", matrix_b.numpy())
print("Matrix Multiplication Result:\n", result_multiplication.numpy())


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication Result:
 [[19 22]
 [43 50]]


Element-wise Operations:
Element-wise operations involve performing a specific operation on corresponding elements of two tensors. TensorFlow supports a variety of element-wise operations, such as addition (tf.add()), subtraction (tf.subtract()), multiplication (tf.multiply()), division (tf.divide()), and more.

In [9]:
# Create two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

# Element-wise multiplication
result_elementwise_multiplication = tf.multiply(matrix_a, matrix_b)

print("Matrix A:\n", matrix_a.numpy())
print("Matrix B:\n", matrix_b.numpy())
print("Element-wise Multiplication Result:\n", result_elementwise_multiplication.numpy())


Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Element-wise Multiplication Result:
 [[ 5 12]
 [21 32]]


# PART-2 : PRACTICAL IMPLEMENTATION

## Talk 1: Creating and Manipulating Matricek

## Tc Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix Ac

In [10]:
matrix_A = tf.random.normal(shape=(2, 2), mean=0.0, stddev=1.0, dtype=tf.float32)

print("Matrix A:\n", matrix_A.numpy())

Matrix A:
 [[ 1.0482087  -0.65394056]
 [ 0.634363    0.6054456 ]]


## Cc Create a Gaussian matrix B with dimensions x, using TensorFlow's truncated_normal function. Display the values of matrix Bc

In [11]:
matrix_b = tf.random.truncated_normal(shape=(3,3) , mean=0.0 , stddev=1.0 , dtype=tf.float32)

print("Matrix B:\n" , matrix_b.numpy())

Matrix B:
 [[-0.45757392 -0.10285349 -0.29860345]
 [ 0.03120783 -0.68269473  0.9113709 ]
 [-0.13505842  0.652817    1.7889283 ]]


## =c Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.x, using TensorFlow's random.normal function. Display the values of matrix Cc

In [15]:
matrix_c = tf.random.normal(shape=(2,2) , mean=2 , stddev=0.5)

print("Matrix C:\n" , matrix_c.numpy())

Matrix C:
 [[2.0552678 2.1233082]
 [1.8495889 1.6727371]]


## ~c Perform matrix addition between matrix A and matrix B, and store the result in matrix Dc

In [23]:
matrix_D = tf.add(matrix_A, matrix_B)

In [24]:
print("Matrix D (Result of A + B):\n",matrix_D.numpy())

Matrix D (Result of A + B):
 [[ 0.58284646 -0.09697807]
 [ 2.6204906   0.09031644]]


## wc Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.

In [21]:
matrix_E = tf.add(matrix_c,matrix_D)

print("MATRIX E (RESULT OF C * D):\n")
print(matrix_E.numpy())

MATRIX E (RESULT OF C * D):

[[2.6381142 2.02633  ]
 [4.4700794 1.7630535]]


## TASK-2 : Per;orming Additional Matrix Operationk

## Tc Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform functionc

In [26]:
matrix_f = tf.random.uniform(shape=(2,2) , minval=0.0 , maxval=1.0 , dtype=tf.float32)

print("MATRIX F:\n")
print(matrix_f.numpy())

MATRIX F:

[[0.8490422  0.90814507]
 [0.02607036 0.33539367]]


## Cc Calculate the transpose of matrix F and store the result in matrix Gc

In [28]:
matrix_G = tf.transpose(matrix_f)
matrix_G.numpy()

array([[0.8490422 , 0.02607036],
       [0.90814507, 0.33539367]], dtype=float32)

## =c Calculate the elementDwise exponential of matrix F and store the result in matrix Hc

In [29]:
matrix_H = tf.exp(matrix_f)
matrix_H.numpy()

array([[2.3374069, 2.4797184],
       [1.0264132, 1.3984908]], dtype=float32)

## ~c Create a matrix I by concatenating matrix F and matrix G horizontallyc

In [32]:
matrix_I = tf.concat([matrix_f, matrix_G], axis=1)
matrix_I.numpy()

array([[0.8490422 , 0.90814507, 0.8490422 , 0.02607036],
       [0.02607036, 0.33539367, 0.90814507, 0.33539367]], dtype=float32)

## wc Create a matrix J by concatenating matrix F and matrix H vertically.

In [33]:
matrix_J = tf.concat([matrix_f , matrix_H] , axis=0)
matrix_J.numpy()

array([[0.8490422 , 0.90814507],
       [0.02607036, 0.33539367],
       [2.3374069 , 2.4797184 ],
       [1.0264132 , 1.3984908 ]], dtype=float32)